language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "io.js"
after_script: ./node_modules/.bin/istanbul cover ./node_modules/tape/bin/tape tests/test-*.js --report lcovonly && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
webhooks:
  urls: https://webhooks.gitter.im/e/237280ed4796c19cc626
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
sudo: false
